# Generated by Django 5.1.2 on 2024-10-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Conteudo')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='Criado em')),
                ('tags', models.ManyToManyField(to='core.tag', verbose_name='Tags')),
            ],
        ),
    ]
